import { Article, NewsResponse, Category } from "@/types/news";

const API_KEY = process.env.NEXT_PUBLIC_NEWS_API_KEY || "";
const BASE_URL = "https://newsapi.org/v2";

async function fetchNews(endpoint: string, params: Record<string, string> = {}): Promise<NewsResponse> {
  const searchParams = new URLSearchParams({
    apiKey: API_KEY,
    ...params,
  });

  const res = await fetch(`${BASE_URL}/${endpoint}?${searchParams}`, {
    next: { revalidate: 600 },
  });

  if (!res.ok) {
    throw new Error(`Failed to fetch news: ${res.status}`);
  }

  return res.json();
}

export async function getTopHeadlines(
  category: Category = "general",
  pageSize: number = 20,
  country: string = "us"
): Promise<Article[]> {
  const data = await fetchNews("top-headlines", {
    category,
    pageSize: String(pageSize),
    country,
  });
  return data.articles.filter((a) => a.title !== "[Removed]");
}

export async function searchNews(
  query: string,
  pageSize: number = 20
): Promise<Article[]> {
  const data = await fetchNews("everything", {
    q: query,
    pageSize: String(pageSize),
    sortBy: "publishedAt",
    language: "en",
  });
  return data.articles.filter((a) => a.title !== "[Removed]");
}

export function generateArticleId(article: Article): string {
  return Buffer.from(article.url).toString("base64url");
}

export function decodeArticleId(id: string): string {
  return Buffer.from(id, "base64url").toString("utf-8");
}

// ── Category-aware mock data ──────────────────────────────────────────

const MOCK_BY_CATEGORY: Record<string, { titles: string[]; descriptions: string[]; sources: string[]; authors: string[] }> = {
  general: {
    titles: [
      "Global Markets Rally as Economic Data Exceeds Expectations",
      "Climate Summit: World Leaders Agree on New Emissions Targets",
      "Archaeological Discovery Rewrites Ancient Civilization Timeline",
      "G7 Nations Pledge Cooperation on AI Safety Framework",
      "UN Report Warns of Accelerating Biodiversity Loss",
      "Infrastructure Bill Passes With Bipartisan Support",
      "Central Banks Signal Coordinated Rate Decision Ahead",
      "Tensions Rise in Pacific as Naval Exercises Expand",
      "Global Supply Chain Shows Signs of Full Recovery",
      "New International Treaty Addresses Deep-Sea Mining",
      "Election Results Shake Up Political Landscape in Europe",
      "Humanitarian Aid Reaches Remote Disaster-Hit Regions",
      "World Economic Forum Highlights Inequality Concerns",
      "Cross-Border Trade Agreement Enters Final Negotiations",
      "Population Growth Slows to Lowest Rate in Decades",
      "Historic Peace Agreement Signed After Years of Conflict",
      "Immigration Reform Debate Intensifies Across Western Nations",
      "Pandemic Preparedness Plan Unveiled by Health Officials",
    ],
    descriptions: [
      "Markets around the world saw significant gains as recent economic indicators pointed to stronger-than-expected growth across multiple sectors.",
      "In a historic agreement, world leaders committed to aggressive new carbon reduction targets at the annual climate summit.",
      "An extraordinary archaeological find is challenging established timelines for early human civilizations.",
      "Leading nations announce comprehensive framework for governing artificial intelligence development and deployment.",
      "A landmark report reveals the accelerating decline of global biodiversity, calling for urgent protective measures.",
      "The wide-ranging infrastructure legislation secures funding for roads, bridges, broadband, and clean energy projects.",
      "Major central banks coordinate messaging ahead of anticipated interest rate decisions that could affect global markets.",
      "Military exercises in the Pacific region draw attention as geopolitical tensions continue to evolve.",
      "Indicators show that global supply chains are approaching pre-pandemic efficiency levels after years of disruption.",
      "Nations gather to establish regulations governing the extraction of minerals from the ocean floor.",
      "Unexpected electoral outcomes are reshaping the political landscape across several European countries.",
      "International relief organizations successfully deliver critical supplies to areas devastated by recent natural disasters.",
      "The annual gathering of business and political leaders focuses on rising inequality and potential solutions.",
      "Negotiators work toward finalizing a comprehensive cross-border trade agreement that could reshape commerce.",
      "Global population growth has slowed significantly, with demographic shifts creating new economic challenges.",
      "After years of negotiations, a landmark peace agreement brings hope to a conflict-affected region.",
      "Debate over immigration reform reaches a critical juncture as nations balance security with humanitarian concerns.",
      "Health officials present a comprehensive plan designed to improve global readiness for future pandemics.",
    ],
    sources: ["Reuters", "BBC News", "The Guardian", "Associated Press", "Al Jazeera", "The Washington Post"],
    authors: ["John Smith", "Maria Garcia", "Alex Chen", "Sarah Johnson", "David Kim", "Emma Wilson"],
  },
  business: {
    titles: [
      "Tech Giants Report Record Quarterly Earnings Amid AI Boom",
      "Federal Reserve Signals Potential Rate Cut in Coming Months",
      "Startup Valuations Surge as Venture Capital Returns",
      "Major Merger Creates World's Largest Retail Conglomerate",
      "Cryptocurrency Markets See Renewed Institutional Interest",
      "Supply Chain Innovation Reduces Costs for Major Retailers",
      "Small Business Optimism Reaches Five-Year High",
      "Banking Sector Faces New Regulatory Oversight Measures",
      "Global Trade Volume Hits Record Levels Despite Tensions",
      "Private Equity Firms Shift Focus to Sustainable Investments",
      "Labor Market Remains Tight as Wages Continue to Climb",
      "IPO Market Rebounds With Several High-Profile Listings",
      "Consumer Spending Patterns Shift Toward Experiences",
      "Real Estate Markets Show Mixed Signals Across Regions",
      "Manufacturing Output Increases for Fourth Consecutive Month",
      "Corporate Bond Market Attracts Record Investment Flows",
      "Fintech Disruption Accelerates in Emerging Markets",
      "Retail Giants Invest Heavily in Same-Day Delivery",
    ],
    descriptions: [
      "Major technology companies have reported unprecedented revenue growth, driven largely by investments in AI infrastructure.",
      "The central bank hinted at easing monetary policy as inflation shows signs of stabilizing across key metrics.",
      "Venture capital is flowing back into the startup ecosystem, pushing valuations higher across technology sectors.",
      "A landmark merger deal creates a retail powerhouse with operations spanning multiple continents and categories.",
      "Large financial institutions are increasing their cryptocurrency holdings as regulatory clarity improves worldwide.",
      "New logistics technologies and AI-driven optimization are helping major retailers cut supply chain costs significantly.",
      "A new survey shows small business owners are the most optimistic they have been in years about economic conditions.",
      "Regulators announce enhanced oversight measures for the banking sector aimed at preventing systemic risks.",
      "Despite ongoing geopolitical tensions, global trade volumes have reached unprecedented levels in the latest quarter.",
      "Private equity firms are increasingly directing capital toward companies with strong environmental credentials.",
      "Employers continue to face hiring challenges as the labor market remains historically tight across most sectors.",
      "The IPO market has come roaring back with several high-profile technology companies going public this quarter.",
      "Consumer spending is increasingly shifting from goods to experiences, reshaping retail and hospitality industries.",
      "Real estate markets are showing divergent trends, with some regions booming while others face correction risks.",
      "Manufacturing output has posted gains for the fourth straight month, signaling sustained industrial recovery.",
      "The corporate bond market is attracting record inflows as investors seek stable returns in uncertain times.",
      "Financial technology companies are rapidly expanding their presence in developing economies worldwide.",
      "Major retailers are pouring billions into logistics infrastructure to meet growing demand for rapid delivery.",
    ],
    sources: ["Bloomberg", "Financial Times", "CNBC", "Wall Street Journal", "Forbes", "The Economist"],
    authors: ["Robert Chen", "Lisa Wang", "Michael Torres", "Jennifer Blake", "Andrew Park", "Diana Ross"],
  },
  technology: {
    titles: [
      "Breakthrough in Quantum Computing Could Transform Industry",
      "AI Revolution: How Machine Learning Is Reshaping Healthcare",
      "Cybersecurity Alert: Major Vulnerability Found in Popular Software",
      "New Chip Architecture Promises 10x Performance Gains",
      "Open Source AI Models Challenge Big Tech Dominance",
      "Augmented Reality Glasses Finally Ready for Mainstream",
      "Cloud Computing Market Exceeds $1 Trillion Valuation",
      "Robotics Advances Enable Fully Automated Warehouses",
      "5G Expansion Reaches Rural Communities Worldwide",
      "Quantum-Safe Encryption Standard Officially Adopted",
      "Brain-Computer Interface Achieves Clinical Milestone",
      "Autonomous Vehicles Get Green Light in Major Cities",
      "New Programming Language Gains Rapid Developer Adoption",
      "Edge Computing Revolution Transforms IoT Applications",
      "Digital Twin Technology Reshapes Urban Planning",
      "Semiconductor Shortage Finally Easing After Years",
      "Tech Companies Race to Build Next-Gen Data Centers",
      "AI Code Assistants Now Write 40% of New Software",
    ],
    descriptions: [
      "Scientists have achieved a major milestone in quantum computing, demonstrating practical applications that could revolutionize data processing.",
      "From diagnosis to drug discovery, artificial intelligence is fundamentally changing how medicine approaches patient care.",
      "Security researchers have identified a critical vulnerability affecting millions of users worldwide.",
      "A revolutionary new processor architecture achieves unprecedented performance gains while reducing power consumption.",
      "Open-source AI models are rapidly closing the gap with proprietary systems, disrupting the technology landscape.",
      "After years of development, augmented reality glasses have reached the quality and price point needed for mass adoption.",
      "The global cloud computing market has surpassed one trillion dollars as businesses accelerate digital transformation.",
      "Advanced robotics systems now handle end-to-end warehouse operations without human intervention.",
      "5G networks are extending their reach into underserved rural areas, bridging the digital connectivity gap.",
      "Governments worldwide adopt a new encryption standard designed to withstand future quantum computing attacks.",
      "A brain-computer interface has achieved a significant clinical milestone, restoring communication for paralyzed patients.",
      "Autonomous vehicle services receive regulatory approval to operate without safety drivers in several major metropolitan areas.",
      "A new programming language is seeing explosive growth among developers, praised for its performance and safety features.",
      "Edge computing solutions are transforming how Internet of Things devices process and transmit data in real time.",
      "Cities are increasingly using digital twin technology to simulate and optimize urban development plans.",
      "The global semiconductor supply chain is showing clear signs of normalization after years of acute shortages.",
      "Technology companies are investing billions to construct next-generation data centers optimized for AI workloads.",
      "AI-powered code assistants are now responsible for generating a significant portion of all new software code.",
    ],
    sources: ["TechCrunch", "Wired", "Ars Technica", "The Verge", "MIT Technology Review", "ZDNet"],
    authors: ["Kevin Lee", "Priya Sharma", "James Wright", "Sophie Martin", "Omar Hassan", "Yuki Tanaka"],
  },
  science: {
    titles: [
      "Space Exploration: New Mission to Mars Announces Launch Date",
      "CERN Physicists Discover New Subatomic Particle",
      "Ocean Floor Mapping Reveals Unknown Mountain Range",
      "Gene Therapy Breakthrough Offers Hope for Rare Diseases",
      "James Webb Telescope Captures Most Distant Galaxy Ever Seen",
      "Scientists Create First Synthetic Living Cell",
      "Climate Model Predictions Prove Remarkably Accurate",
      "New Element Added to the Periodic Table After Lab Synthesis",
      "Antarctic Ice Core Reveals 2 Million Years of Climate Data",
      "Nuclear Fusion Reactor Achieves Net Energy Gain Milestone",
      "Dark Matter Detection Experiment Reports Promising Signal",
      "Biodiversity Study Identifies 10,000 New Species",
      "Mars Rover Discovers Evidence of Ancient Microbial Life",
      "Gravitational Wave Observatory Detects Unexpected Event",
      "Artificial Photosynthesis System Outperforms Natural Plants",
      "Neanderthal DNA Analysis Rewrites Human Migration History",
      "Deep Sea Expedition Finds New Ecosystems Near Hydrothermal Vents",
      "Quantum Entanglement Record Broken Across 1,200 Kilometers",
    ],
    descriptions: [
      "The international space agency has confirmed a launch window for the most ambitious Mars mission yet attempted.",
      "Physicists at CERN have confirmed the discovery of a previously unknown subatomic particle with unexpected properties.",
      "Advanced sonar technology has revealed a previously unknown underwater mountain range spanning thousands of kilometers.",
      "A new gene therapy approach has shown remarkable success in clinical trials for treating rare genetic disorders.",
      "The James Webb Space Telescope has captured images of the most distant galaxy ever observed by humanity.",
      "Researchers have created the first fully synthetic living cell, marking a milestone in synthetic biology.",
      "A comprehensive review shows that decades-old climate models have been remarkably accurate in their predictions.",
      "Scientists have successfully synthesized a new element, expanding our understanding of the periodic table.",
      "Ice cores extracted from Antarctica provide an unprecedented 2-million-year record of Earth's climate history.",
      "A nuclear fusion reactor has achieved the long-sought milestone of producing more energy than was used to start the reaction.",
      "The world's most sensitive dark matter detector has reported signals that could confirm the existence of dark matter particles.",
      "A massive global study has identified thousands of previously unknown species across diverse ecosystems.",
      "NASA's Mars rover has found chemical signatures consistent with ancient microbial life in Martian rock samples.",
      "Gravitational wave detectors have captured an unexpected signal that challenges current astrophysical models.",
      "An artificial photosynthesis system has been developed that converts sunlight to energy more efficiently than natural plants.",
      "New analysis of Neanderthal DNA is reshaping our understanding of early human migration patterns and interbreeding.",
      "A deep-sea expedition has discovered entirely new ecosystems thriving near previously unknown hydrothermal vents.",
      "Scientists have demonstrated quantum entanglement over a record distance of 1,200 kilometers using satellite technology.",
    ],
    sources: ["Nature", "Science Magazine", "New Scientist", "Scientific American", "NASA", "National Geographic"],
    authors: ["Dr. Elena Vasquez", "Prof. James Chen", "Dr. Amara Osei", "Dr. Henrik Larsson", "Prof. Mei Lin", "Dr. Carlos Ruiz"],
  },
  health: {
    titles: [
      "Universal Flu Vaccine Shows Promise in Late-Stage Trials",
      "Mental Health Crisis Among Youth Prompts New Guidelines",
      "Breakthrough Drug Slows Alzheimer's Progression Significantly",
      "WHO Declares End to Global Mpox Emergency",
      "Exercise Found More Effective Than Medication for Depression",
      "New Cancer Treatment Achieves 90% Remission Rate in Trials",
      "Global Life Expectancy Reaches All-Time High of 74 Years",
      "Gut Microbiome Research Reveals Links to Autoimmune Diseases",
      "Telemedicine Usage Permanently Doubles After Pandemic",
      "New Antibiotic Effective Against Drug-Resistant Bacteria",
      "Sleep Research Uncovers Critical Role in Memory Formation",
      "Plant-Based Diets Linked to 25% Lower Heart Disease Risk",
      "Personalized Medicine Approach Transforms Cancer Treatment",
      "Wearable Health Monitors Detect Diseases Before Symptoms",
      "Childhood Obesity Rates Begin to Decline After Decades",
      "CRISPR Gene Editing Used to Cure Sickle Cell Disease",
      "Air Pollution Linked to Cognitive Decline in New Study",
      "Universal Healthcare Expansion Reaches Milestone in 40 Nations",
    ],
    descriptions: [
      "A universal influenza vaccine has shown remarkable efficacy in advanced clinical trials, potentially ending seasonal flu epidemics.",
      "Health authorities issue updated guidelines addressing the growing mental health crisis among children and adolescents.",
      "A newly developed drug has demonstrated the ability to significantly slow cognitive decline in Alzheimer's patients.",
      "The World Health Organization officially lifts the global emergency designation for the mpox outbreak.",
      "A large-scale study confirms that regular exercise outperforms standard antidepressant medication for treating mild to moderate depression.",
      "An experimental cancer treatment has achieved extraordinary remission rates in clinical trials across multiple tumor types.",
      "Global average life expectancy has reached a historic high, driven by advances in medicine and public health.",
      "New research establishes strong connections between gut bacteria composition and the development of autoimmune conditions.",
      "Telemedicine adoption has permanently increased, fundamentally changing how patients access healthcare services worldwide.",
      "Researchers have developed a new antibiotic that proves effective against several strains of drug-resistant bacteria.",
      "Groundbreaking sleep research reveals the critical mechanisms by which sleep enables memory consolidation and learning.",
      "A comprehensive study demonstrates that plant-based dietary patterns are associated with significantly lower cardiovascular risk.",
      "Personalized treatment approaches based on genetic profiling are dramatically improving outcomes for cancer patients.",
      "Advanced wearable health monitoring devices can now detect early signs of disease before clinical symptoms appear.",
      "For the first time in decades, childhood obesity rates are showing meaningful declines in several developed nations.",
      "CRISPR-based gene editing therapy has successfully cured patients with sickle cell disease in clinical trials.",
      "A major new study links long-term exposure to air pollution with accelerated cognitive decline in older adults.",
      "Forty nations have now achieved meaningful universal healthcare coverage, marking a global public health milestone.",
    ],
    sources: ["The Lancet", "WHO News", "Medical News Today", "JAMA", "WebMD", "Health Affairs"],
    authors: ["Dr. Sarah Mitchell", "Dr. Raj Patel", "Dr. Anna Schmidt", "Dr. Marcus Green", "Dr. Keiko Yamada", "Dr. Luis Fernandez"],
  },
  sports: {
    titles: [
      "Olympic Committee Reveals Host City for 2036 Games",
      "World Cup Qualifiers Produce Shocking Upsets",
      "Tennis Legend Announces Retirement After Grand Slam Win",
      "Formula 1 Introduces Revolutionary Engine Regulations",
      "NBA Draft Class Called Best in a Generation",
      "Cricket World Cup Final Breaks Viewership Records",
      "Women's Soccer League Secures Historic Broadcasting Deal",
      "Marathon World Record Shattered by 45 Seconds",
      "Esports Officially Recognized for Olympic Inclusion",
      "NFL Expands to 18-Game Regular Season",
      "Rising Golf Star Wins Major Championship at Age 21",
      "Rugby World Cup Draws Record Global Audience",
      "New Anti-Doping Technology Catches More Cheaters",
      "College Athletics Undergoes Massive Revenue-Sharing Reform",
      "Surfing Competition Sees Record Wave Heights",
      "Boxing Unification Bout Becomes Most-Watched Fight Ever",
      "Paralympic Games Set New Records for Participation",
      "Baseball Implements Radical Rule Changes for New Season",
    ],
    descriptions: [
      "After months of deliberation, the IOC has selected the host city for the 2036 Summer Olympic Games.",
      "The latest round of World Cup qualifying matches has produced several unexpected results that shake up group standings.",
      "A tennis icon caps off an extraordinary career with a final Grand Slam title before announcing retirement.",
      "Formula 1 announces a complete overhaul of engine regulations designed to make racing more competitive and sustainable.",
      "Basketball analysts are calling this year's NBA draft class the most talented collection of prospects in recent memory.",
      "The Cricket World Cup final attracted the largest television audience ever recorded for the sport.",
      "A women's professional soccer league has signed a groundbreaking multi-billion dollar broadcasting agreement.",
      "A marathon runner has obliterated the world record, finishing nearly a minute faster than the previous best time.",
      "The International Olympic Committee votes to include esports as a medal event in upcoming Olympic Games.",
      "The NFL officially approves an expansion to an 18-game regular season schedule starting next year.",
      "A 21-year-old golfer becomes the youngest player in decades to win a major championship tournament.",
      "The Rugby World Cup has drawn its largest global television audience, cementing the sport's growing international appeal.",
      "Advanced testing technology developed by anti-doping agencies is proving more effective at detecting prohibited substances.",
      "A landmark agreement establishes revenue sharing between colleges and student athletes, transforming college sports.",
      "A professional surfing competition features record-breaking wave heights that challenge the world's best surfers.",
      "A boxing unification bout has become the most-watched fight in the history of the sport globally.",
      "The Paralympic Games achieve record numbers of participating athletes and nations in this year's competition.",
      "Major League Baseball introduces significant rule changes aimed at speeding up games and increasing excitement.",
    ],
    sources: ["ESPN", "Sky Sports", "BBC Sport", "Sports Illustrated", "The Athletic", "Bleacher Report"],
    authors: ["Chris Anderson", "Maria Santos", "Tom Bradley", "Rachel Kim", "Patrick O'Brien", "Aisha Mbeki"],
  },
  entertainment: {
    titles: [
      "Streaming Wars Intensify as New Platforms Launch",
      "Award Season Surprise: Independent Film Sweeps Oscars",
      "Music Industry Revenue Hits All-Time High on Streaming Growth",
      "Video Game Release Breaks First-Week Sales Records",
      "Broadway Returns to Record Attendance Numbers",
      "K-Pop Group's World Tour Becomes Highest-Grossing Ever",
      "Acclaimed Director Announces Ambitious Sci-Fi Trilogy",
      "Podcast Industry Reaches 500 Million Global Listeners",
      "Virtual Reality Concert Attracts 10 Million Viewers",
      "Classic Film Franchise Announces Reboot With New Cast",
      "Independent Bookstores See Surprising Renaissance",
      "Music Festival Season Draws Record Crowds Worldwide",
      "Animation Studio's Latest Film Breaks Box Office Records",
      "Celebrity Chef Opens Chain of Community-Focused Restaurants",
      "Documentary Series on Ocean Life Becomes Most-Watched Ever",
      "Legendary Band Announces Final Reunion Tour",
      "AI-Generated Art Sparks Intense Debate in Creative World",
      "Theater Production Combines Live Acting With Holograms",
    ],
    descriptions: [
      "The streaming landscape continues to evolve rapidly as new competitors enter the market with exclusive content.",
      "In a stunning upset, a low-budget independent film dominated the Academy Awards, winning multiple major categories.",
      "The global music industry has achieved record-breaking revenue, driven primarily by the continued growth of streaming.",
      "A highly anticipated video game has shattered first-week sales records across all major gaming platforms.",
      "Broadway shows are attracting audiences at rates that surpass even pre-pandemic levels, signaling a cultural revival.",
      "A K-Pop group's latest world tour has become the highest-grossing concert tour in music history.",
      "An acclaimed filmmaker reveals plans for an ambitious science fiction trilogy spanning three decades of story.",
      "The global podcast industry has reached a major milestone, with half a billion regular listeners worldwide.",
      "A virtual reality concert event attracted an unprecedented 10 million simultaneous viewers from around the globe.",
      "A beloved classic film franchise announces a complete reboot with an exciting new ensemble cast attached.",
      "Independent bookstores are experiencing a surprising resurgence, driven by community events and curated selections.",
      "Music festivals around the world are reporting record attendance as live entertainment demand surges.",
      "The latest animated feature film has broken multiple box office records in its opening weekend worldwide.",
      "A celebrity chef is expanding a restaurant concept focused on serving affordable meals in underserved communities.",
      "A documentary series exploring ocean life has become the most-watched nature documentary in streaming history.",
      "A legendary rock band announces what they say will be their final reunion tour, spanning 50 cities worldwide.",
      "The use of AI-generated art in commercial projects has ignited fierce debate about creativity and copyright.",
      "An innovative theater production seamlessly blends live actors with holographic technology for an immersive experience.",
    ],
    sources: ["Variety", "Rolling Stone", "Entertainment Weekly", "The Hollywood Reporter", "Billboard", "Deadline"],
    authors: ["Jessica Palmer", "Ryan Cooper", "Natalie Fox", "Brandon Hayes", "Olivia Chen", "Marcus Thompson"],
  },
};

const MOCK_IMAGES = [
  "https://picsum.photos/seed/news1/800/500",
  "https://picsum.photos/seed/news2/800/500",
  "https://picsum.photos/seed/news3/800/500",
  "https://picsum.photos/seed/news4/800/500",
  "https://picsum.photos/seed/news5/800/500",
  "https://picsum.photos/seed/news6/800/500",
  "https://picsum.photos/seed/news7/800/500",
  "https://picsum.photos/seed/news8/800/500",
  "https://picsum.photos/seed/news9/800/500",
  "https://picsum.photos/seed/news10/800/500",
  "https://picsum.photos/seed/news11/800/500",
  "https://picsum.photos/seed/news12/800/500",
  "https://picsum.photos/seed/news13/800/500",
  "https://picsum.photos/seed/news14/800/500",
  "https://picsum.photos/seed/news15/800/500",
  "https://picsum.photos/seed/news16/800/500",
  "https://picsum.photos/seed/news17/800/500",
  "https://picsum.photos/seed/news18/800/500",
];

export function getMockArticles(count: number = 12, category: string = "general"): Article[] {
  const catData = MOCK_BY_CATEGORY[category] || MOCK_BY_CATEGORY.general;
  const totalTitles = catData.titles.length;

  return Array.from({ length: Math.min(count, totalTitles) }, (_, i) => ({
    source: {
      id: null,
      name: catData.sources[i % catData.sources.length],
    },
    author: catData.authors[i % catData.authors.length],
    title: catData.titles[i % totalTitles],
    description: catData.descriptions[i % totalTitles],
    url: `https://example.com/${category}-article-${i + 1}`,
    urlToImage: MOCK_IMAGES[(i + (category.charCodeAt(0) % 6)) % MOCK_IMAGES.length],
    publishedAt: new Date(Date.now() - i * 3600000).toISOString(),
    content: catData.descriptions[i % totalTitles] + " The story continues with detailed analysis and expert commentary on the implications of these developments.",
  }));
}
